Practica_M6_Camila_Palma/proyecto_vehiculos_django/config/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView, name='index'),
    path('', include('usuarios.urls')),
    path('vehiculos/', include('vehiculos.urls')),
]

Practica_M6_Camila_Palma/proyecto_vehiculos_django/usuarios/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('registro/', views.UserRegistroView.as_view(), name='registro'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
]

Practica_M6_Camila_Palma/proyecto_vehiculos_django/vehiculos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('list/', views.VehiculosView.as_view(), name='lista_vehiculos'),
    path('add/', views.VehiculoCreateView.as_view(), name='add_vehiculos'),
]

Practica_M6_Camila_Palma/proyecto_vehiculos_django/usuarios/models.py
from django.db import models

# Create your models here.

Practica_M6_Camila_Palma/proyecto_vehiculos_django/vehiculos/models.py
from django.db import models

class Vehiculo(models.Model):
    tipo_vehiculo = [
        ('Particular', 'Particular'),
        ('Transporte', 'Transporte'),
        ('Carga', 'Carga'),
    ]
    marcas = [
        ('Fiat', 'Fiat'),
        ('Chevrolet', 'Chevrolet'),
        ('Ford', 'Ford'),
        ('Toyota', 'Toyota'),
    ]
    
    marca = models.CharField(max_length=20, blank=False, null=False, choices=marcas, default='Ford')
    modelo = models.CharField(max_length=100, blank=False, null=False)
    serial_carroceria = models.CharField (max_length=50, blank=False, null=False)
    serial_motor = models.CharField (max_length=50, blank=False, null=False)
    categoria = models.CharField(max_length=50, blank=False, null=False, choices=tipo_vehiculo, default='Particular')
    precio = models.IntegerField(blank=False, null=False)
    fecha_creacion = models.DateTimeField(null=False, blank=False, auto_now_add=True)
    fecha_modificacion = models.DateTimeField(null=False, blank=False, auto_now_add=False, auto_now=True)

    def condicion_precio(self):
        """Determina la condición del precio según el valor del vehículo."""
        if self.precio <= 10000:
            return 'Bajo'
        elif self.precio <= 30000:
            return 'Medio'
        else:
            return 'Alto'
        
    def __str__(self) -> str:
        return f"Marca: {self.marca} - Modelo: {self.modelo} - Serial carroceria: {self.serial_carroceria} - Serial motor: {self.serial_motor} Categoria: {self.categoria} - Precio: {self.precio}"

        
        super().save(*args, **kwargs)
    
    class Meta:
        permissions = [("can_edit_vehiculos", "Puede agregar, visualizar, modificar vehículos (no puede eliminar)")]
        ordering = ['precio']
        
    

Practica_M6_Camila_Palma/proyecto_vehiculos_django/config/views.py
from django.shortcuts import render


def IndexView(request):
    
    return render(request, 'index.html', {})

Practica_M6_Camila_Palma/proyecto_vehiculos_django/usuarios/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.http.response import HttpResponse as HttpResponse
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.contrib import messages

from django.contrib.auth.models import Permission


# VISTA BASADA EN CLASE PARA REGISTRO
class UserRegistroView(CreateView):
    form_class =  UserCreationForm
    template_name = 'usuarios/registro.html'
    success_url = reverse_lazy('login')
    
    def form_valid(self, form):
        
        response = super().form_valid(form)
        usuario = form.instance # obtenemos la istancia de la Clase User
        # permiso = Permission.objects.get(codename='can_edit_clubes') # obtener permiso desde la base de datos
        # usuario.user_permissions.add(permiso) # le agregamos el permiso al usuario
        usuario.save()

        messages.success(self.request, 'Registro exitoso.')
        return response
    
    


class UserLoginView(LoginView):
    template_name = 'usuarios/login.html'
    redirect_authenticated_user = True
    success_url = reverse_lazy('index')

    
    def form_valid(self, form):
        
        messages.success(self.request, 'Login exitoso.')
        return super().form_valid(form)
    
    def get_success_url(self) -> str:
        return self.get_redirect_url() or self.success_url
    
    

class UserLogoutView(LogoutView):
    next_page = 'index'
    
    def dispatch(self, request, *args, **kwargs):
        messages.success(self.request, 'Ha cerrado la sesión exitosamente.')
        return super().dispatch(request, *args, **kwargs)
    

Practica_M6_Camila_Palma/proyecto_vehiculos_django/vehiculos/views.py
from django.forms import BaseModelForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages
from django import forms

from .models import Vehiculo


    

# LoginRequiredMixin, PermissionRequiredMixin
class VehiculosView(LoginRequiredMixin, ListView):
    model = Vehiculo
    template_name = "vehiculos/vehiculos.html"
    context_object_name = 'vehiculos'
    login_url = reverse_lazy('login')  
    redirect_field_name = 'next'


    

class VehiculoCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Vehiculo
    template_name = "vehiculos/create_vehiculo.html"
    fields = ['marca', 'modelo', 'serial_carroceria', 'serial_motor', 'categoria', 'precio']
    success_url = reverse_lazy('lista_vehiculos')
    permission_required = 'can.add_vehiculo_model'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    
    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            messages.error(self.request, "Usted no tiene el nivel de acceso para acceder a la vista.")
            return redirect("lista_vehiculos")
        
        else:
            messages.info(self.request, "Primero debe iniciar sesión para continuar.")
            return redirect("login")
        
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['modelo'].widget = forms.TextInput(attrs={'class': 'form-control'})
        form.fields['serial_carroceria'].widget = forms.TextInput(attrs={'class': 'form-control'})
        form.fields['serial_motor'].widget = forms.TextInput(attrs={'class': 'form-control'})
        form.fields['precio'].widget = forms.TextInput(attrs={'class': 'form-control'})
        return form
    

Practica_M6_Camila_Palma/proyecto_vehiculos_django/templates/index.html
{% extends "layouts/base.html" %}
{% block contenido %}

<main class="container py-5">
    <section>
        <h1 class="text-center py-3">Catalogo de Vehículos</h1>
    </section>
    <hr>
    <section>

    </section>
</main>


{% endblock contenido %}

Practica_M6_Camila_Palma/proyecto_vehiculos_django/templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>App de vehiculos</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static "css/styles.css" %}">


</head>
<body>

    {% include "partials/navbar.html" %}

    {% include "partials/visor_mensajes.html" %}

    {% block contenido %}
    
    {% endblock contenido %}
    
</body>
</html>

Practica_M6_Camila_Palma/proyecto_vehiculos_django/templates/partials/navbar.html
<header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url "index" %}" class="nav-link px-2 text-white">Vehículos</a></li>
          <li><a href="{% url "index" %}" class="nav-link px-2 text-white">Inicio</a></li>
          {% if perms.vehiculos.add_vehiculo %}
          <li><a href="{% url "add_vehiculos" %}" class="nav-link px-2 text-secondary">Agregar</a></li>
          {% endif %}
          <li><a href="{% url "lista_vehiculos" %}" class="nav-link px-2 text-secondary">Listar</a></li>
        </ul>

        {% if not user.is_authenticated %}
        <div class="text-end">
          <a class="btn btn-outline-light me-2" href="{% url "login" %}">Login</a>
          <a class="btn btn-warning" href="{% url "registro" %}">Sign-up</a>         
        </div>
        {% endif %}

        {% if user.is_authenticated %}
        <form method="post" action="{% url "logout" %}" class="ms-3">
            {% csrf_token %}
            <button type="input" class="btn btn-danger">Logout</button>
        </form>
        {% endif %}
      </div>
    </div>
  </header>


  <script>

  </script>

Practica_M6_Camila_Palma/proyecto_vehiculos_django/templates/partials/visor_mensajes.html
<section>
    {% if  messages %}
        {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                <strong>{{message.tags}}</strong> {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
</section>

Practica_M6_Camila_Palma/proyecto_vehiculos_django/templates/usuarios/login.html
{% extends "layouts/base.html" %}


{% block contenido %}

<main class="container">
    <section>
        <h1 class="text-center py-5">Página de login de usuario</h1>
    </section>
    <section>
        <div class="row justify-content-center">
            <div class="col-12 col-md-5 col-lg-4">
                <form method="post">
                    {% csrf_token %}
                    {{form}}
                    <input type="submit" value="Iniciar sesión" class="btn btn-primary">
                </form>
            </div>
        </div>
    </section>
</main>

{% endblock contenido %}

Practica_M6_Camila_Palma/proyecto_vehiculos_django/templates/usuarios/registro.html
{% extends "layouts/base.html" %}


{% block contenido %}
<header>
    <h1>Página de registro de usuarios</h1>
</header>

<main class="container">
    <section>
        <form method="post">
            {% csrf_token %}
            {{form}}

            <input type="submit" value="Crear usuario">
        </form>
    </section>
</main>

{% endblock contenido %}

Practica_M6_Camila_Palma/proyecto_vehiculos_django/templates/vehiculos/create_vehiculo.html
{% extends "layouts/base.html" %}


{% block contenido %}

<header>
    <h1 class="text-center">Agrega un nuevo Vehículo</h1>
</header>

<main class="container py-3">
    <section>

        <div class="row justify-content-center">
            <div class="col-12 col-md-6">
                <form enctype="multipart/form-data" method="post">
                    {% csrf_token %}
                    {{form}}
                    <div class="d-flex justify-content">
                       <input type="submit" class="btn border my-3" value="Enviar"> 
                    </div>
                    
                </form>
            </div>
        </div>
    </section>
</main>

{% endblock contenido %}

Practica_M6_Camila_Palma/proyecto_vehiculos_django/templates/vehiculos/vehiculos.html
{% extends "layouts/base.html" %}

{% block contenido %}

<header>
    <h1 class="text-center">Listado de Vehículos</h1>
</header>

<section id='lista_vehiculos'>
    <table>
        <thead>
            <tr>
                <th>Marca</th>
                <th>Modelo</th>
                <th>Serial Carrocería</th>
                <th>Serial Motor</th>
                <th>Categoría</th>
                <th>Precio</th>
                <th>Condición de Precio</th>
            </tr>
        </thead>
        <tbody>
            {% for vehiculo in vehiculos %}
                <tr>
                    <td>{{ vehiculo.marca }}</td>
                    <td>{{ vehiculo.modelo }}</td>
                    <td>{{ vehiculo.serial_carroceria }}</td>
                    <td>{{ vehiculo.serial_motor }}</td>
                    <td>{{ vehiculo.categoria }}</td>
                    <td>{{ vehiculo.precio }}</td>
                    <td>{{ vehiculo.condicion_precio }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="6" style="text-align: center;">No hay vehículos disponibles.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</section>

{% endblock contenido %}